### ISSUE TITLE
🎨 [Style] 프로필

### ISSUE THREAD

**Issue by easyxxu** [FRONTENDSCHOOL5/final-23-Food-zip#25]
## TODO
- [x] 상대방 프로필과 나의 프로필의 겹치는 부분 컴포넌트로 구현
- [x] 상대방 프로필 : 채팅 버튼, 팔로우 버튼, 공유하기 버튼 
- [x] 나의 프로필 : 프로필 수정 버튼, 상품 등록 버튼
- [x] 사용자가 작성한 게시물을 앨범형으로 볼 수 있도록 구현
- [x] 상단바의 더보기 버튼을 통해 설정 및 개인정보, 로그아웃 모달 구현
- [x] 게시글 컴포넌트

**Comment by yyuli** [comment]
프로필 완료
