### ISSUE TITLE
🎨 [Style] 게시글

### ISSUE THREAD

**Issue by easyxxu** [FRONTENDSCHOOL5/final-23-Food-zip#26]
## TODO
- [ ] 게시글 댓글 확인 페이지
- [ ] 게시글 댓글 신고하기(모달)
- [ ] 게시글 작성
- [ ] 게시글 이미지 등록 버튼
